### ISSUE TITLE
Authors can end up with the same actor

### ISSUE THREAD

**Issue by kicowobuha** [dualmoon/Cogs.v3#11]
There is no check in place before the dictionary data is set that multiple authors were not assigned the A proposal: an array with identifiers for each actor. If two authors have the same identifier, assign new identifiers.

**Comment by dualmoon** [comment]
Reading the docs closer, `random.choices()` does _not_ necessarily return unique values from the list. Will switch to `random.sample()` instead.

**Comment by dualmoon** [comment]
Fixed!!
